# This build file uses template features from YAML so it is generic enough for
# any Bob project. Don't modify it unless you know what you're doing.


# Definition of our build pipeline order
stages:
  - build
  - deploy
  - pypi


# Build targets
.build_template: &build_job
  stage: build
  before_script:
    - export PATH=/opt/miniconda/bin:/usr/local/bin:$PATH
    - git clean -ffdx
    - mkdir _ci
    - curl --silent "https://gitlab.idiap.ch/bob/bob.admin/raw/condapackage/gitlab/install.sh" > _ci/install.sh
    - chmod 755 _ci/install.sh
    - ./_ci/install.sh _ci #updates
  script:
    - ./_ci/build.sh
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - conda-env/.pkgs/*.tar.bz2
      - conda-env/.pkgs/urls.txt
      - conda-env/src_cache
  artifacts:
    expire_in: 1 week
    paths:
      - _ci/
      - dist/
      - conda-env/$OS_SLUG/


build_linux_27:
  <<: *build_job
  variables:
    PYTHON_VERSION: "2.7"
  tags:
    - docker
  image: continuumio/conda_builder_linux

build_linux_35:
  <<: *build_job
  variables:
    PYTHON_VERSION: "3.5"
  tags:
    - docker
  image: continuumio/conda_builder_linux

build_linux_36:
  <<: *build_job
  variables:
    PYTHON_VERSION: "3.6"
    BUILD_EGG: "true"
  tags:
    - docker
  image: continuumio/conda_builder_linux

build_macosx_27:
  <<: *build_job
  variables:
    PYTHON_VERSION: "2.7"
  tags:
    - conda-macosx

build_macosx_35:
  <<: *build_job
  variables:
    PYTHON_VERSION: "3.5"
  tags:
    - conda-macosx

build_macosx_36:
  <<: *build_job
  variables:
    PYTHON_VERSION: "3.6"
  tags:
    - conda-macosx


# Deploy targets
deploy_beta:
  stage: deploy
  environment: beta
  only:
    - master
    - condapackage
    - /^v\d+\.\d+\.\d+([abc]\d*)?$/  # PEP-440 compliant version (tags)
  before_script:
    - ./_ci/install.sh _ci #updates
  script:
    - ./_ci/deploy_beta.sh
  dependencies:
    - build_linux_27
    - build_linux_35
    - build_linux_36
    - build_macosx_27
    - build_macosx_35
    - build_macosx_36
  tags:
    - deployer


pypi:
  stage: pypi
  environment: pypi
  only:
    - /^v\d+\.\d+\.\d+([abc]\d*)?$/  # PEP-440 compliant version (tags)
  except:
    - branches
  before_script:
    - ./_ci/install.sh _ci #updates
  script:
    - ./_ci/pypi.sh
  dependencies:
    - build_linux_27
    - build_linux_35
    - build_linux_36
    - build_macosx_27
    - build_macosx_35
    - build_macosx_36
  tags:
    - deployer
