python:
  - 2.7
  - 3.5
  - 3.6
numpy:
  - 1.12
  - 1.13
gcc:
  - 4.8.5
libgcc:
  - 4.8.5
toolchain:
  - 2.3.2
boost:
  - 1.61
libblitz:
  - 0.10
libpng:
  - 1.6.27
giflib:
  - 5.1.4
jpeg:
  - 9b
sox:
  - 14.4.2
hdf5:
  - 1.8.17
libmatio:
  - 1.5.6
ffmpeg:
  - 2.8.10
vlfeat:
  - 0.9.20
libsvm:
  - 3.21
mkl:
  - 2017.0.1
sqlite:
  - 3.13.0
zlib:
  - 1.2.8
xz:
  - 5.2.2
x264:
  - 20131217
libogg:
  - 1.3.2

pin_run_as_build:
  libgcc:
    min_pin: x.x.x
    max_pin: ''
  boost:
    max_pin: x.x
  libblitz:
    max_pin: x.x
  libpng:
    max_pin: x.x
  giflib:
    max_pin: x
  jpeg:
    max_pin: x
  sox:
    max_pin: x.x.x
  hdf5:
    max_pin: x.x.x
  libmatio:
    max_pin: x.x
  ffmpeg:
    max_pin: x.x
  vlfeat:
    max_pin: x.x.x
  libsvm:
    max_pin: x.x
  zlib:
    max_pin: x.x.x
  xz:
    max_pin: x
  x264:
    max_pin: x.x.x
  libogg:
    max_pin: x
  bob.buildout:
    max_pin: x
  bob.extension:
    max_pin: x
  bob.blitz:
    max_pin: x
  bob.core:
    max_pin: x
  bob.io.base:
    max_pin: x
  bob.io.image:
    max_pin: x
  bob.io.matlab:
    max_pin: x
  bob.io.video:
    max_pin: x
  bob.ip.color:
    max_pin: x
  bob.ip.draw:
    max_pin: x
  bob.ip.optflow.liu:
    max_pin: x
  bob.learn.activation:
    max_pin: x
  bob.learn.boosting:
    max_pin: x
  bob.learn.boosting:
    max_pin: x
  bob.learn.libsvm:
    max_pin: x
  bob.math:
    max_pin: x
  bob.measure:
    max_pin: x
  bob.sp:
    max_pin: x
  bob.ap:
    max_pin: x
  bob.db.base:
    max_pin: x
  bob.db.mnist:
    max_pin: x
  bob.db.wine:
    max_pin: x
  bob.io.audio:
    max_pin: x
  bob.ip.base:
    max_pin: x
  bob.ip.facedetect:
    max_pin: x
  bob.ip.flandmark:
    max_pin: x
  bob.ip.gabor:
    max_pin: x
  bob.ip.optflow.hornschunck:
    max_pin: x
  bob.ip.qualitymeasure:
    max_pin: x
  bob.ip.dlib:
    max_pin: x
  bob.learn.linear:
    max_pin: x
  bob.learn.mlp:
    max_pin: x
  bob.db.atnt:
    max_pin: x
  bob.db.iris:
    max_pin: x
  bob.learn.em:
    max_pin: x
  bob:
    max_pin: x
  bob.db.arface:
    max_pin: x
  bob.db.asvspoof:
    max_pin: x
  bob.db.asvspoof2017:
    max_pin: x
  bob.db.atvskeystroke:
    max_pin: x
  bob.db.avspoof:
    max_pin: x
  bob.db.banca:
    max_pin: x
  bob.db.biosecure:
    max_pin: x
  bob.db.biosecurid.face:
    max_pin: x
  bob.db.casme2:
    max_pin: x
  bob.db.caspeal:
    max_pin: x
  bob.db.cohface:
    max_pin: x
  bob.db.frgc:
    max_pin: x
  bob.db.gbu:
    max_pin: x
  bob.db.hci_tagging:
    max_pin: x
  bob.db.ijba:
    max_pin: x
  bob.db.kboc16:
    max_pin: x
  bob.db.lfw:
    max_pin: x
  bob.db.livdet2013:
    max_pin: x
  bob.db.mobio:
    max_pin: x
  bob.db.msu_mfsd_mod:
    max_pin: x
  bob.db.multipie:
    max_pin: x
  bob.db.nist_sre12:
    max_pin: x
  bob.db.pericrosseye:
    max_pin: x
  bob.db.putvein:
    max_pin: x
  bob.db.replay:
    max_pin: x
  bob.db.replaymobile:
    max_pin: x
  bob.db.scface:
    max_pin: x
  bob.db.utfvp:
    max_pin: x
  bob.db.voicepa:
    max_pin: x
  bob.db.xm2vts:
    max_pin: x
  bob.db.youtube:
    max_pin: x
  bob.ip.caffe_extractor:
    max_pin: x
  bob.ip.facelandmarks:
    max_pin: x
  bob.ip.skincolorfilter:
    max_pin: x
  bob.kaldi:
    max_pin: x
  gridtk:
    max_pin: x
  bob.bio.base:
    max_pin: x
  bob.bio.face:
    max_pin: x
  bob.bio.gmm:
    max_pin: x
  bob.bio.spear:
    max_pin: x
  bob.bio.video:
    max_pin: x
  bob.db.cuhk_cufs:
    max_pin: x
  bob.db.voxforge:
    max_pin: x
  bob.pad.base:
    max_pin: x
  bob.pad.voice:
    max_pin: x
  bob.bio.caffe_face:
    max_pin: x
