{% set name = 'bob.buildout' %}
{% set project_dir = environ.get('RECIPE_DIR') + '/..' %}

package:
  name: {{ name }}
  version: {{ environ.get('BOB_PACKAGE_VERSION', '0.0.1') }}

build:
  number: {{ environ.get('BOB_BUILD_NUMBER', 0) }}
  run_exports:
    - {{ pin_subpackage(name) }}
  script:
    - cd {{ project_dir }}
    {% if environ.get('BUILD_EGG') %}
    - python setup.py sdist --formats=zip
    {% endif %}
    - python setup.py install --single-version-externally-managed --record record.txt
    # installs the documentation source, readme to share/doc so it is available
    # during test time
    - install -d "${PREFIX}/share/doc/{{ name }}"
    - cp -R README.rst requirements.txt doc "${PREFIX}/share/doc/{{ name }}/"

requirements:
  host:
    - python {{ python }}
    - setuptools {{ setuptools }}
    - zc.recipe.egg {{ zc_recipe_egg }}
    - nose {{ nose }}
    - pytest {{ pytest }}
    - pytest-cov {{ pytest_cov }}
    - coverage {{ coverage }}
    - sphinx {{ sphinx }}
    - sphinx_rtd_theme {{ sphinx_rtd_theme }}
  run:
    - python
    - setuptools
    - {{ pin_compatible('zc.recipe.egg') }}
    - {{ pin_compatible('nose') }}
    - {{ pin_compatible('pytest') }}
    - {{ pin_compatible('pytest-cov') }}
    - {{ pin_compatible('coverage') }}
    - {{ pin_compatible('sphinx') }}
    - {{ pin_compatible('sphinx_rtd_theme') }}

test:
  imports:
    - {{ name }}
  commands:
    - sphinx-build -aEW ${PREFIX}/share/doc/{{ name }}/doc sphinx
    - if [ -n "${CI_PROJECT_DIR}" ]; then mv sphinx "${CI_PROJECT_DIR}/"; fi
    - sphinx-build -aEb doctest ${PREFIX}/share/doc/{{ name }}/doc sphinx
    # runs tests for package only, report only what is in the package
    # creates html and xml reports and place them in specific directories
    - pytest --verbose --cov {{ name }} --cov-report term-missing --cov-report html:{{ project_dir }}/sphinx/coverage --cov-report xml:{{ project_dir }}/coverage.xml --pyargs {{ name }}
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name }}  # [osx]

about:
  home: https://www.idiap.ch/software/bob/
  summary: A collection of zc.buildout recipes for Bob packages
  license: BSD 3-Clause
  license_family: BSD
